### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by HongguiWu1** [lmcinnes/glasbey#1]
Hi Leland,
When I install it with "pip install glasbey", I met the following ERROR message:

ERROR: Package 'glasbey' requires a different Python: 3.9.13 not in '>=3.10'

Do you have any idea how to solve it?

**Comment by lmcinnes** [comment]
The version on PyPI currently requires at least Python 3.10. The current main branch supports python 3.9, so you could install from there:

```bash
pip install git+https://github.com/lmcinnes/glasbey
``` 

Hopefully the next release will not be too far off, and that will also support python 3.9
