### ISSUE TITLE
Error when importing: cannot import name 'get_cmap' from 'matplotlib.cm'

### ISSUE THREAD

**Issue by nine9ths** [lmcinnes/glasbey#13]
```
Python 3.10.8 (main, Nov 20 2022, 18:49:12) [Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glasbey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/..snip../venv/lib/python3.10/site-packages/glasbey/__init__.py", line 1, in <module>
    from ._glasbey import create_palette, extend_palette, create_block_palette
  File "/..snip../venv/lib/python3.10/site-packages/glasbey/_glasbey.py", line 16, in <module>
    from ._converters import get_rgb_palette, palette_to_sRGB1
  File "/..snip../venv/lib/python3.10/site-packages/glasbey/_converters.py", line 7, in <module>
    from matplotlib.cm import get_cmap
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (/..snip../venv/lib/python3.10/site-packages/matplotlib/cm.py)
```
After installing with `pip install glasbey` I get some this error on both Intel and Apple Silicon. I've tried with Python 3.10 and 3.12. Using pip to uninstall/reinstall matplotlib doesn't seem to make a difference.

**Comment by lmcinnes** [comment]
Do you know what version of matplotlib you have installed?

**Comment by nine9ths** [comment]
Yeah, `pip list`:

```
matplotlib                3.9.0
matplotlib-inline         0.1.7
```

**Comment by pmbaumgartner** [comment]
I was encountering this error and browsing other ways to get glasbey palettes, and noticed this error pop up in the [`colorcet` documentation](https://colorcet.holoviz.org/user_guide/index.html#using-colorcet-via-matplotlib-cm-get-cmap). 

```
/tmp/ipykernel_2445/1693774644.py:3: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  get_cmap("cet_fire")
```

**Comment by lmcinnes** [comment]
It might be a matter of moving to matplotlib.colormaps from matplotlib.cm? I'll see if I can figure out something that will work for all cases (backwards compatibility with older matplotlib will be useful for a while as well).

**Comment by lmcinnes** [comment]
I'm not really able to find much free time to look at this, so I'm afraid it might be a little while...

**Comment by lmcinnes** [comment]
I managed to find a little time and I think I have it fixed.
