### ISSUE TITLE
Consider not including matplotlib in install dependencies?

### ISSUE THREAD

**Issue by tlambert03** [lmcinnes/glasbey#7]
Hi and thanks for the snappy glasbey implementation here.

I work on a number of visualization libs (napari, and related projects), and am making a new lightweight [cmap](https://github.com/tlambert03/cmap) library for those who need, but don't want to bring on big dependencies like matplotlib.  I'd *like* to include this library as the functional backing for glasbey, but the dependency on matplotlib is a dealbreaker.  (ideally, numba would also be optional, but I can see how that's the a lot of the crux of what this library has to offer over the previous implementation).

I wonder if you'd consider vendoring just the few conversion functions you need from matplotlib, and making any export to matplotlib colormap instances lazily import matplotlib?  (if someone is exporting to matplotlib colormap, it's likely they have it installed in their environment, but those who want a lean glasbey implementation don't necessarily)

I'd happily make a PR to this effect, but want to gauge your openness first.

thanks!

**Comment by lmcinnes** [comment]
I am definitely open to having lighter requirements. If cmap provides the easy conversion functions for colours then lazily loading matplotlib in the case of a named colormap being given sounds fine to me. I would definitely welcome a PR for this if you have the time. Thanks!

**Comment by tlambert03** [comment]
see #8 ... and see the note where I decided to close it.  As mentioned there, this can be reopened if you're also really wanting to reduce the dependencies.  but no need to on my behalf i think :)  thanks again

**Comment by tlambert03** [comment]
also, after rereading this thread and response, I just want to clarify: I wasn't proposing that you use `cmap` instead of matplotlib ... I was proposing that you make matplotlib (and preferably scikit-learn) optional so that `cmap` could depend on `glasbey` without also taking on heavier sub-dependencies.
